services:
  backend:
    build: .
    image: ishika1214/aesthetic-notes-backend:prod
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    restart: always